### ISSUE TITLE
Icon used for success green box doesn't display correctly

### ISSUE THREAD

**Issue by irojasag** [brolag/quedateencasacr#1]
As you can see on the attached image, the icon used doesn't work

![image](https://user-images.githubusercontent.com/18739832/78206799-09000c00-745d-11ea-9863-95c483bcf8dc.png)

**Comment by irojasag** [comment]
Neither on the code 
https://github.com/brolag/quedateencasacr/blob/376eb6f8c6a5266f19026a092f0f631d4f65e945/src/QuedateEnCasaCr.js#L157-L163

![image](https://user-images.githubusercontent.com/18739832/78206839-26cd7100-745d-11ea-9fd0-c151bef19424.png)

**Comment by brolag** [comment]
Thanks @irojasag ! I'll fix it right away!
